using FrenchExDev.Net.CSharp.Object.Builder2;

namespace FrenchExDev.Net.Vagrant.Commands.Builders;

/// <summary>
/// Provides a base class for building Vagrant command objects using a fluent interface. Supports configuration of
/// command options, environment variables, and output handlers for standard output and error streams.
/// </summary>
/// <remarks>This class is intended to be inherited by specific Vagrant command builders. It allows customization
/// of command execution parameters, such as working directory, output formatting, and environment variables. Output
/// handlers can be registered to process standard output and error messages generated by the command. The builder
/// enforces that a valid working directory is set before command execution.</remarks>
/// <typeparam name="TBuilder">The type of the concrete builder implementing this class. Enables fluent method chaining with the correct builder
/// type.</typeparam>
/// <typeparam name="TCommand">The type of the Vagrant command object to be constructed. Must implement the IVagrantCommand interface.</typeparam>
public abstract class VagrantCommandBuilder<TBuilder, TCommand> : AbstractBuilder<TCommand>
    where TCommand : class, IVagrantCommand
    where TBuilder : VagrantCommandBuilder<TBuilder, TCommand>
{
    protected string? _workingDirectory;
    protected bool? _noColor;
    protected bool? _machineReadable;
    protected bool? _version;
    protected bool? _debug;
    protected bool? _timestamp;
    protected bool? _debugTimestamp;
    protected bool? _noTty;
    protected bool? _help;
    protected Dictionary<string, string> _environmentVariables = new();
    protected List<Func<string, Task>> _onStdErr = [];
    protected List<Func<string, Task>> _onStdOut = [];

    /// <summary>
    /// Registers a callback to be invoked for each line of standard output produced by the process.
    /// </summary>
    /// <remarks>Multiple callbacks can be registered; each will be invoked in the order added when standard
    /// output is received.</remarks>
    /// <param name="func">An action delegate that receives each line of standard output as a string. Cannot be null.</param>
    /// <returns>The current builder instance, enabling method chaining.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to the type specified by TBuilder.</exception>
    public TBuilder OnStdOut(Func<string, Task> func)
    {
        _onStdOut.Add(func);
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Registers a callback to be invoked for each line written to the standard error stream.
    /// </summary>
    /// <remarks>Multiple callbacks can be registered; each will be invoked in the order added when standard
    /// error output is received.</remarks>
    /// <param name="func">An action delegate that receives each line of standard error output as a string. Cannot be null.</param>
    /// <returns>The current builder instance, enabling method chaining.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to the type specified by TBuilder.</exception>
    public TBuilder OnStdErr(Func<string, Task> func)
    {
        _onStdErr.Add(func);
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Adds or updates an environment variable for the process being configured.
    /// </summary>
    /// <remarks>If an environment variable with the specified name already exists, its value is overwritten.
    /// This method is typically used in fluent configuration scenarios.</remarks>
    /// <param name="name">The name of the environment variable to set. Cannot be null or empty.</param>
    /// <param name="value">The value to assign to the environment variable. Can be null to remove the variable.</param>
    /// <returns>The builder instance with the specified environment variable set, enabling method chaining.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to the type specified by <typeparamref name="TBuilder"/>.</exception>
    public TBuilder EnvironmentVariable(string name, string value)
    {
        _environmentVariables[name] = value;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Configures whether colored output is enabled for the builder.
    /// </summary>
    /// <param name="with">Specifies whether colored output should be enabled. If <see langword="true"/>, colored output is enabled; if
    /// <see langword="false"/>, colored output is disabled; if <see langword="null"/>, the default behavior is used.</param>
    /// <returns>The current builder instance with the updated color configuration.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to <typeparamref name="TBuilder"/>.</exception>
    public TBuilder Color(bool? with = true)
    {
        _noColor = with is false ? false : null;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Configures the builder to disable color output.
    /// </summary>
    /// <param name="noColor">A value indicating whether color output should be disabled. If <see langword="true"/>, color output is disabled;
    /// if <see langword="false"/>, color output is enabled. If <see langword="null"/>, the default behavior is used.</param>
    /// <returns>The builder instance with the updated color output configuration.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to <typeparamref name="TBuilder"/>.</exception>
    public TBuilder NoColor(bool? noColor = true)
    {
        _noColor = noColor;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Configures whether the output should be formatted for machine readability.
    /// </summary>
    /// <param name="machineReadable">A value indicating whether the output should be machine-readable. If <see langword="true"/>, the output will be
    /// structured for automated processing; if <see langword="false"/>, the output may be optimized for human
    /// readability. If <see langword="null"/>, the default behavior is applied.</param>
    /// <returns>The current builder instance with the machine-readable setting applied.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to the specified builder type <typeparamref name="TBuilder"/>.</exception>
    public TBuilder MachineReadable(bool? machineReadable = true)
    {
        _machineReadable = machineReadable;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Sets whether the builder should include version information in the generated output.
    /// </summary>
    /// <param name="version">A value indicating whether version information should be included. If <see langword="true"/>, version
    /// information is included; if <see langword="false"/>, it is omitted. If <see langword="null"/>, the default
    /// behavior is used.</param>
    /// <returns>The current builder instance with the updated version setting.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to <typeparamref name="TBuilder"/>.</exception>
    public TBuilder Version(bool? version = true)
    {
        _version = version;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Enables or disables debug mode for the builder.
    /// </summary>
    /// <param name="debug">A value indicating whether debug mode should be enabled. If <see langword="true"/>, debug mode is enabled; if
    /// <see langword="false"/>, debug mode is disabled. If <see langword="null"/>, the debug state is reset to its
    /// default value.</param>
    /// <returns>The current builder instance with the updated debug setting.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to the type specified by <typeparamref name="TBuilder"/>.</exception>
    public TBuilder Debug(bool? debug = true)
    {
        _debug = debug;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Configures whether timestamps are included in the output.
    /// </summary>
    /// <param name="timestamp">A value indicating whether to include timestamps. If <see langword="true"/>, timestamps will be added; if <see
    /// langword="false"/>, they will be omitted. If <see langword="null"/>, the default behavior is used.</param>
    /// <returns>The builder instance with the timestamp configuration applied.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to the builder type <typeparamref name="TBuilder"/>.</exception>
    public TBuilder Timestamp(bool? timestamp = true)
    {
        _timestamp = timestamp;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Enables or disables the inclusion of debug timestamps in the output generated by the builder.
    /// </summary>
    /// <param name="debugTimestamp">A value indicating whether debug timestamps should be included. If <see langword="true"/>, timestamps are added;
    /// if <see langword="false"/>, they are omitted. If <c>null</c>, the default behavior is applied.</param>
    /// <returns>The current builder instance with the debug timestamp setting applied.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to the type specified by <typeparamref name="TBuilder"/>.</exception>
    public TBuilder DebugTimestamp(bool? debugTimestamp = true)
    {
        _debugTimestamp = debugTimestamp;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Configures the builder to disable allocation of a pseudo-terminal (TTY) for the process being started.
    /// </summary>
    /// <param name="noTty">Specifies whether to disable TTY allocation. If <see langword="true"/>, the process will not be allocated a
    /// pseudo-terminal. If <see langword="false"/>, TTY allocation may be enabled. If <see langword="null"/>, the
    /// default behavior is used.</param>
    /// <returns>The builder instance with the updated TTY allocation setting.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to the type specified by <typeparamref name="TBuilder"/>.</exception>
    public TBuilder NoTty(bool? noTty = true)
    {
        _noTty = noTty;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Enables or disables help text generation for the current builder instance.
    /// </summary>
    /// <param name="help">A value indicating whether help text should be generated. If <see langword="true"/>, help text is enabled; if
    /// <see langword="false"/>, help text is disabled. If <c>null</c>, the default behavior is used.</param>
    /// <returns>The current builder instance with the updated help setting.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to <typeparamref name="TBuilder"/>.</exception>
    public TBuilder Help(bool? help = true)
    {
        _help = help;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Sets the working directory to be used by the builder.
    /// </summary>
    /// <param name="wd">The path of the working directory to set. Can be absolute or relative. If null or empty, the builder may use a
    /// default directory.</param>
    /// <returns>The current builder instance with the updated working directory.</returns>
    /// <exception cref="InvalidCastException">Thrown if the current instance cannot be cast to the type specified by <typeparamref name="TBuilder"/>.</exception>
    public TBuilder WorkingDirectory(string wd)
    {
        _workingDirectory = wd;
        return this as TBuilder ?? throw new InvalidCastException(nameof(TBuilder));
    }

    /// <summary>
    /// Performs validation logic specific to the current object and records any validation failures encountered.
    /// </summary>
    /// <param name="visitedCollector">A dictionary used to track objects that have already been visited during validation to prevent redundant checks
    /// and circular references.</param>
    /// <param name="failures">A dictionary for collecting validation failures, where each failure is associated with a property name and an
    /// exception describing the issue.</param>
    protected override void ValidateInternal(VisitedObjectDictionary visitedCollector, FailuresDictionary failures)
    {
        if (string.IsNullOrWhiteSpace(_workingDirectory))
        {
            failures.Failure(nameof(WorkingDirectory), new InvalidDataException("Working directory must be set and not empty or whitespace."));
        }
    }
}
