@FrenchExDev.Net.CSharp.ProjectDependency4.Viz.Api_HostAddress = http://localhost:5093

GET {{FrenchExDev.Net.CSharp.ProjectDependency4.Viz.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
